/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.spamfilter.client;

/**
 *
 * @author Admin
 */
public class frmInbox extends javax.swing.JFrame {
    private String serverIP = "10.49.25.229";   // ← IP ZeroTier của máy chạy Server
    // Lưu danh sách email thật để khi click còn lấy được body
    private java.util.List<com.spamfilter.model.EmailMessage> inboxList = new java.util.ArrayList<>();
    private java.util.List<com.spamfilter.model.EmailMessage> spamList = new java.util.ArrayList<>();
    /**
     * Creates new form frmInbox
     */
    public frmInbox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        txtNoiDung = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        btnLamMoi = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblThuDen = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSpam = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNoiDung.setColumns(20);
        txtNoiDung.setRows(5);
        jScrollPane2.setViewportView(txtNoiDung);

        jLabel3.setText("Chi tiết nội dung Email");

        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        tblThuDen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Người gửi", "Tiêu đề", "Thời gian"
            }
        ));
        tblThuDen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThuDenMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblThuDen);

        jTabbedPane1.addTab("Hộp thư đến", jScrollPane3);

        tblSpam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Người gửi", "Tiêu đề", "Thời gian"
            }
        ));
        tblSpam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSpamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSpam);

        jTabbedPane1.addTab("Thư mục Spam", jScrollPane1);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Quản lý Email");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLamMoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane1)
                    .addComponent(jScrollPane2))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(241, 241, 241))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(36, 36, 36)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblThuDenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThuDenMouseClicked
        // TODO add your handling code here:
    int row = tblThuDen.getSelectedRow();
        if (row != -1 && row < inboxList.size()) {
            com.spamfilter.model.EmailMessage email = inboxList.get(row);

            txtNoiDung.setText(
                "--- THÔNG TIN THƯ ĐẾN ---\n"
                + "Người gửi : " + email.getSenderEmail() + "\n"
                + "Tiêu đề   : " + email.getSubject() + "\n"
                + "IP gửi    : " + email.getSenderIP() + "\n\n"
                + "Nội dung:\n" + email.getBody()
            );
        }
    }//GEN-LAST:event_tblThuDenMouseClicked

    private void tblSpamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSpamMouseClicked
        // TODO add your handling code here:
    int row = tblSpam.getSelectedRow();
        if (row != -1 && row < spamList.size()) {
            com.spamfilter.model.EmailMessage email = spamList.get(row);

            txtNoiDung.setText(
                "--- THƯ RÁC (SPAM) ---\n"
                + "Người gửi : " + email.getSenderEmail() + "\n"
                + "Tiêu đề   : " + email.getSubject() + "\n"
                + "IP gửi    : " + email.getSenderIP() + "\n\n"
                + "Nội dung:\n" + email.getBody() + "\n\n"
                + " Email này đã bị hệ thống đánh dấu là Spam!"
            );
        }
    }//GEN-LAST:event_tblSpamMouseClicked

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        txtNoiDung.setText("");

            javax.swing.table.DefaultTableModel modelInbox = (javax.swing.table.DefaultTableModel) tblThuDen.getModel();
            javax.swing.table.DefaultTableModel modelSpam  = (javax.swing.table.DefaultTableModel) tblSpam.getModel();
            modelInbox.setRowCount(0);
            modelSpam.setRowCount(0);

            // Xóa list cũ
            inboxList.clear();
            spamList.clear();

            // Tải dữ liệu
            loadEmails("GET_INBOX", modelInbox, inboxList);
            loadEmails("GET_SPAM",  modelSpam,  spamList);
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void loadEmails(String command,
                            javax.swing.table.DefaultTableModel model,
                            java.util.List<com.spamfilter.model.EmailMessage> targetList) {
        try (java.net.Socket socket = new java.net.Socket(serverIP, 12345);
             java.io.ObjectOutputStream oos = new java.io.ObjectOutputStream(socket.getOutputStream());
             java.io.ObjectInputStream ois = new java.io.ObjectInputStream(socket.getInputStream())) {

            oos.writeObject(command);
            oos.flush();

            @SuppressWarnings("unchecked")
            java.util.List<com.spamfilter.model.EmailMessage> list =
                    (java.util.List<com.spamfilter.model.EmailMessage>) ois.readObject();

            for (com.spamfilter.model.EmailMessage email : list) {
                targetList.add(email);          // lưu object thật
                model.addRow(new Object[]{
                    email.getSenderEmail(),
                    email.getSubject(),
                    java.time.LocalDateTime.now().toString().substring(0, 19)
                });
            }

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Không thể kết nối Server (" + command + "):\n" + ex.getMessage(),
                    "Lỗi kết nối", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int rowThuDen = tblThuDen.getSelectedRow();
        int rowSpam = tblSpam.getSelectedRow();

        javax.swing.table.DefaultTableModel modelThuDen = (javax.swing.table.DefaultTableModel) tblThuDen.getModel();
        javax.swing.table.DefaultTableModel modelSpam = (javax.swing.table.DefaultTableModel) tblSpam.getModel();

        if (rowThuDen != -1) {
            modelThuDen.removeRow(rowThuDen);
            txtNoiDung.setText("");
        } else if (rowSpam != -1) {
            modelSpam.removeRow(rowSpam);
            txtNoiDung.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn thư cần xóa!");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInbox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblSpam;
    private javax.swing.JTable tblThuDen;
    private javax.swing.JTextArea txtNoiDung;
    // End of variables declaration//GEN-END:variables
}
