/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.spamfilter.client;

/**
 *
 * @author PhamVuNguyen
 */
public class frmMain extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmMain.class.getName());

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtServerIP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmailNhan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmailGui = new javax.swing.JTextField();
        btnGuiMail = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtTieuDe = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNoiDung = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("LOGIN");

        jLabel2.setText("Server IP:");

        jLabel3.setText("Email người nhận:");

        jLabel4.setText("Email người gửi:");

        btnGuiMail.setText("Gửi Mail");
        btnGuiMail.addActionListener(this::btnGuiMailActionPerformed);

        jLabel5.setText("Tiêu đề Email:");

        jLabel6.setText("Nội dung Email: ");

        txtNoiDung.setColumns(20);
        txtNoiDung.setRows(5);
        jScrollPane1.setViewportView(txtNoiDung);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                                    .addComponent(txtEmailNhan)
                                    .addComponent(txtEmailGui)
                                    .addComponent(txtServerIP)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnGuiMail, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE))))))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(txtServerIP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(txtEmailGui, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtEmailNhan, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGuiMail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuiMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiMailActionPerformed
        // TODO add your handling code here:
        // 1. Lấy dữ liệu từ giao diện
        String serverIp = txtServerIP.getText().trim();
        String senderEmail = txtEmailGui.getText().trim();
        String recipient = txtEmailNhan.getText().trim();
        String subject = txtTieuDe.getText().trim();
        String body = txtNoiDung.getText().trim();

        // 2. Kiểm tra bỏ trống
        if (serverIp.isEmpty() || senderEmail.isEmpty() || recipient.isEmpty()
                || subject.isEmpty() || body.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Vui lòng điền tất cả các thông tin!",
                    "Cảnh báo", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 3. Kết nối Server và gửi theo protocol mới
        try (java.net.Socket socket = new java.net.Socket(serverIp, 12345);
             java.io.ObjectOutputStream oos = new java.io.ObjectOutputStream(socket.getOutputStream());
             java.io.ObjectInputStream ois = new java.io.ObjectInputStream(socket.getInputStream())) {

            // Lấy IP của máy Client
            String senderIp = socket.getLocalAddress().getHostAddress();

            // Tạo đối tượng email
            com.spamfilter.model.EmailMessage email =
                    new com.spamfilter.model.EmailMessage(senderIp, senderEmail, recipient, subject, body);

            // ---- PROTOCOL MỚI ----
            // Bước 1: Gửi lệnh "SEND"
            oos.writeObject("SEND");
            oos.flush();

            // Bước 2: Gửi object EmailMessage
            oos.writeObject(email);
            oos.flush();

            // Bước 3: Đọc phản hồi từ Server
            com.spamfilter.model.EmailMessage result =
                    (com.spamfilter.model.EmailMessage) ois.readObject();

            // 4. Hiển thị kết quả cho người dùng
            if ("SPAM".equals(result.getStatus())) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Email đã được gửi nhưng bị đưa vào SPAM!\n"
                        + "Tiêu đề: " + result.getSubject(),
                        "Cảnh báo Spam", javax.swing.JOptionPane.WARNING_MESSAGE);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Gửi email thành công!\nThư đã vào Hộp thư đến (INBOX).",
                        "Thành công", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }

            // 5. Xóa trắng form (giữ lại IP Server và Email người gửi)
            txtEmailNhan.setText("");
            txtTieuDe.setText("");
            txtNoiDung.setText("");

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Không thể kết nối tới Server:\n" + ex.getMessage(),
                    "Lỗi kết nối", javax.swing.JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnGuiMailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmMain().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuiMail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtEmailGui;
    private javax.swing.JTextField txtEmailNhan;
    private javax.swing.JTextArea txtNoiDung;
    private javax.swing.JTextField txtServerIP;
    private javax.swing.JTextField txtTieuDe;
    // End of variables declaration//GEN-END:variables
}
